name: Release

# 当 main 分支被 push,就会触发
on:
  push:
    branches: [main]
# 权限
permissions:
  contents: write
  issues: write
  pull-requests: write
  packags: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 签出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 安装 nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: 安装依赖
        run: pnpm install --no-frozen-lockfile

      - name: 构建 dist # 构建，根据自己的仓库构建命令来
        run: |
          pnpm run build

      - name: 发布 npm 包
        run: |
          npm cache clean --force
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
